#!/bin/sh

srcdir=$(dirname $0)
srcdir=${srcdir:-.}
outdir=${srcdir}/out

test -d ${outdir} || mkdir -p ${outdir}
rst2html --template=${srcdir}/site_template.txt ${srcdir}/../../README.rst > ${outdir}/index.html
sphinx-build -A embedded=True -b singlehtml -c ${srcdir} ${srcdir}/.. ${outdir}/documentation
rm -fr ${outdir}/documentation/{.buildinfo,.doctrees,_static,objects.inv}
#sphinx-build -A embedded=True -b singlehtml -c ${srcdir} ${srcdir}/../../configdb ${outdir}/reference
#rm -fr ${outdir}/reference/{.doctree,.static,objects.inv}
